### ISSUE TITLE
data download

### ISSUE THREAD

**Issue by yuan243212790** [hanchenchen/Attention-A-Lightweight-2D-Hand-Pose-Estimation-Approach-Pytorch#2]
where ? datasets

**Comment by hanchenchen** [comment]
It is updated in the README.md

**Comment by yuan243212790** [comment]
>  why there are only 2 pictures in your link in readme？？

**Comment by hanchenchen** [comment]
> why there are only 2 pictures in your link in readme？？

Which one?

**Comment by yuan243212790** [comment]
https://github.com/HowieMa/NSRMhand       in the data_sample/cmuhand

**Comment by hanchenchen** [comment]
here. https://github.com/HowieMa/NSRMhand#training:

> For your convenience, you can download our preprocessed dataset from [here](https://www.dropbox.com/s/ob0pbssocwszh9v/CMUhand.tar?dl=0).

**Comment by yuan243212790** [comment]
OK!thank you! when i run train.py there shows 
Delete last direction!

Process finished with exit code 0
it did not work ,it only work before training.what is the problem?

**Comment by hanchenchen** [comment]
please pull the latest commit: https://github.com/hanchenchen/Attention-A-Lightweight-2D-Hand-Pose-Estimation-Approach-Pytorch/commit/60cddadc9f87a2dd0db2ed53f031fc11fd130300
It is used to avoid rewriting existing log files.

**Comment by yuan243212790** [comment]
> 
when i update your code it shows:
the log directory exists!
it is the same question,it did not work.

**Comment by yuan243212790** [comment]
Traceback (most recent call last):
  File "/home/yuan/Attention-A-Lightweight-2D-Hand-Pose-Estimation-Approach-Pytorch-main/main.py", line 212, in <module>
    train()
  File "/home/yuan/Attention-A-Lightweight-2D-Hand-Pose-Estimation-Approach-Pytorch-main/main.py", line 118, in train
    label_pred = model(img)
  File "/home/yuan/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/yuan/anaconda3/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 166, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/yuan/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/yuan/Attention-A-Lightweight-2D-Hand-Pose-Estimation-Approach-Pytorch-main/model/__init__.py", line 214, in forward
    x = self.dense3(x)
  File "/home/yuan/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/yuan/Attention-A-Lightweight-2D-Hand-Pose-Estimation-Approach-Pytorch-main/model/__init__.py", line 154, in forward
    inputs = self.arb[i](inputs)
  File "/home/yuan/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/yuan/Attention-A-Lightweight-2D-Hand-Pose-Estimation-Approach-Pytorch-main/model/__init__.py", line 72, in forward
    augmented_conv = self.attention_aug(x)
  File "/home/yuan/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/yuan/anaconda3/lib/python3.7/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/home/yuan/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/yuan/Attention-A-Lightweight-2D-Hand-Pose-Estimation-Approach-Pytorch-main/model/attention_augmentation2D.py", line 58, in forward
    flat_q, flat_k, flat_v, q, k, v = self.compute_flat_qkv(x, self.dk, self.dv, self.Nh)
  File "/home/yuan/Attention-A-Lightweight-2D-Hand-Pose-Estimation-Approach-Pytorch-main/model/attention_augmentation2D.py", line 85, in compute_flat_qkv
    q *= dkh ** -0.5
RuntimeError: Output 0 of ReshapeAliasBackward0 is a view and is being modified inplace. This view is the output of a function that returns multiple views. Such functions do not allow the output views to be modified inplace. You should replace the inplace operation by an out-of-place one.

**Comment by yuan243212790** [comment]
which pytorch version do you use? i have the runtimeerror:
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [4, 42, 1, 1]], which is output 0 of ReluBackward0, is at version 1; expected version 0 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!

**Comment by hanchenchen** [comment]
torch==1.7.1+cu101
torchvision==0.8.2+cu101

**Comment by yuan243212790** [comment]
Traceback (most recent call last):
  File "/home/yuan/Attention-A-Lightweight-2D-Hand-Pose-Estimation-Approach/Attention-A-Lightweight-2D-Hand-Pose-Estimation-Approach-Pytorch-main/main.py", line 200, in <module>
    train()
  File "/home/yuan/Attention-A-Lightweight-2D-Hand-Pose-Estimation-Approach/Attention-A-Lightweight-2D-Hand-Pose-Estimation-Approach-Pytorch-main/main.py", line 113, in train
    label_loss.backward()
  File "/home/yuan/anaconda3/lib/python3.7/site-packages/torch/_tensor.py", line 307, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/yuan/anaconda3/lib/python3.7/site-packages/torch/autograd/__init__.py", line 156, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [4, 42, 1, 1]], which is output 0 of ReluBackward0, is at version 1; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

Process finished with exit code 1

hi，do you know how to sovle the loss.backgward() probem?

**Comment by hanchenchen** [comment]
> RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [4, 42, 1, 1]], which is output 0 of ReluBackward0, is at version 1; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

I don’t know.. And I can’t reproduce this error

**Comment by yuan243212790** [comment]
hi,i sovled the probem by installing the same enviroment torch 1.7+cuda11
